# Generated by Django 5.0.6 on 2024-07-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_id', models.PositiveSmallIntegerField()),
                ('course_description', models.CharField(max_length=20)),
                ('course_credit', models.PositiveSmallIntegerField()),
                ('course_start_date', models.CharField(max_length=20)),
                ('course_end_date', models.CharField(max_length=20)),
                ('course_category', models.CharField(max_length=20)),
                ('course_teacher', models.CharField(max_length=20)),
                ('course_capacity', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
