# Generated by Django 5.0.6 on 2024-07-16 08:08


# Generated by Django 5.0.6 on 2024-07-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='default_phone_number', max_length=20)),
                ('class_start_date', models.CharField(max_length=20)),
                ('class_end_date', models.CharField(max_length=20)),
                ('class_capacity', models.PositiveSmallIntegerField()),
                ('class_location', models.CharField(max_length=20)),
                ('class_teacher', models.CharField(max_length=20)),
                ('enrolled_students', models.CharField(max_length=20)),
                ('class_description', models.CharField(max_length=20)),
                ('class_id', models.PositiveSmallIntegerField()),
                ('class_hours', models.PositiveSmallIntegerField()),
            ],
        ),
    ]

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('class', '0001_initial'),
#     ]

#     operations = [
#         migrations.CreateModel(
#             name='Class',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('class_name', models.CharField(default='default_phone_number', max_length=20)),
#                 ('class_start_date', models.CharField(max_length=20)),
#                 ('class_end_date', models.CharField(max_length=20)),
#                 ('class_capacity', models.PositiveSmallIntegerField()),
#                 ('class_location', models.CharField(max_length=20)),
#                 ('class_teacher', models.CharField(max_length=20)),
#                 ('enrolled_students', models.CharField(max_length=20)),
#                 ('class_description', models.CharField(max_length=20)),
#                 ('class_id', models.PositiveSmallIntegerField()),
#                 ('class_hours', models.PositiveSmallIntegerField()),
#             ],
#         ),
#         migrations.DeleteModel(
#             name='Class',
#         ),
#     ]
