# Generated by Django 5.0.6 on 2024-07-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='default_address', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(default='default_parent_name', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone_number',
            field=models.CharField(default='default_pparent_hone_number', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='default_phone_number', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
